# name: Keep Render App Awake

on:
  schedule:
    - cron: "*/6 * * * *" 
  workflow_dispatch:       # Allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping your Render App
        run: curl -s https://devsnippet.onrender.com > /dev/null
